export const PLATFORM_GUIDE_USER_ID = '__journeyhub_platform_guide__';
export const PLATFORM_GUIDE_NAME = 'JourneyHub Guide';
export const SPARK_BOT_NAME = 'Spark Bot';
export const SPARK_BOT_ID = '__journeyhub_spark_bot__';
export const FUTURE_SELF_BOT_ID = '__journeyhub_future_self__';

export function futureSelfName() {
  return `You (${new Date().getFullYear() + 1})`;
}

export const BADGE_DEFS = {
  contributor: { label: 'Active Contributor', css: 'badge-contributor', minPosts: 5 },
  expert: { label: 'Helpful Expert', css: 'badge-expert', minLikesReceived: 20 },
  starter: { label: 'Conversation Starter', css: 'badge-starter', minThreads: 3 },
  friendly: { label: 'Community Friend', css: 'badge-friendly', minFollowers: 5 },
};

export const RESOURCE_LIBRARY = [
  {
    id: 'journeyhub-guide',
    title: 'JourneyHub Guide DM',
    category: 'AI Coach',
    description: 'Ask the built-in guide anything about the platform, from navigation to how to use growth tools.',
    tags: ['onboarding', 'navigation', 'questions', 'ai help'],
    actionLabel: 'Open Messages',
    route: 'messages',
  },
  {
    id: 'profile-reflection',
    title: 'Profile Reflection',
    category: 'Self-Discovery',
    description: 'Sharpen your profile so other people can understand your goals, strengths, and journey quickly.',
    tags: ['clarity', 'identity', 'goals', 'reflection'],
    actionLabel: 'Open Profile',
    route: 'profile',
  },
  {
    id: 'life-journey',
    title: 'Life Journey Prompts',
    category: 'Reflection',
    description: 'Use the life journey section to tell your story and invite thoughtful responses from others.',
    tags: ['story', 'meaning', 'support', 'self-awareness'],
    actionLabel: 'View Profiles',
    route: 'profiles',
  },
  {
    id: 'growth-paths',
    title: 'Growth Paths',
    category: 'Planning',
    description: 'Build a milestone-based growth path with accountability, updates, and collaborators.',
    tags: ['habits', 'milestones', 'accountability', 'planning'],
    actionLabel: 'Open Growth',
    route: 'growth',
  },
  {
    id: 'community-match',
    title: 'Suggested Communities',
    category: 'Connection',
    description: 'Discover communities that fit your current goals, interests, and who you already follow.',
    tags: ['community', 'networking', 'shared interests', 'support'],
    actionLabel: 'Browse Communities',
    route: 'communities',
  },
  {
    id: 'following-feed',
    title: 'Following Feed',
    category: 'Signals',
    description: 'See updates, reflections, and posts from people you follow so you can learn in context.',
    tags: ['feed', 'inspiration', 'updates', 'signals'],
    actionLabel: 'Open Following',
    route: 'following',
  },
  {
    id: 'community-insights',
    title: 'Community Insights',
    category: 'Analysis',
    description: 'Use AI tools like Community DNA, consensus maps, and member trajectory to spot patterns.',
    tags: ['analysis', 'patterns', 'insight', 'research'],
    actionLabel: 'Open Insights',
    route: 'insights',
  },
  {
    id: 'thread-starter',
    title: 'Thread Starter',
    category: 'Expression',
    description: 'Draft a thread about a goal, obstacle, or question and turn it into conversation.',
    tags: ['writing', 'feedback', 'discussion', 'support'],
    actionLabel: 'Create Thread',
    route: 'newThread',
  },
  {
    id: 'direct-messages',
    title: 'Direct Messages',
    category: 'Connection',
    description: 'Reach out one-to-one for encouragement, accountability, and guidance.',
    tags: ['mentor', 'support', '1:1', 'help'],
    actionLabel: 'Open Messages',
    route: 'messages',
  },
  {
    id: 'coursera',
    title: 'Coursera',
    category: 'Learning',
    description: 'Take structured courses and professional certificates for skill-building and career growth.',
    collection: 'Career Tools',
    tags: ['courses', 'career', 'skills', 'certificates'],
    actionLabel: 'Visit Coursera',
    route: 'external',
    externalUrl: 'https://www.coursera.org/',
  },
  {
    id: 'khan-academy',
    title: 'Khan Academy',
    category: 'Learning',
    description: 'Use free lessons and practice to strengthen fundamentals at your own pace.',
    collection: 'Career Tools',
    tags: ['free learning', 'practice', 'education', 'skills'],
    actionLabel: 'Visit Khan Academy',
    route: 'external',
    externalUrl: 'https://www.khanacademy.org/',
  },
  {
    id: 'meetup',
    title: 'Meetup',
    category: 'Community',
    description: 'Find local and virtual groups to learn together and build accountability around shared interests.',
    collection: 'Career Tools',
    tags: ['events', 'groups', 'networking', 'community'],
    actionLabel: 'Visit Meetup',
    route: 'external',
    externalUrl: 'https://www.meetup.com/',
  },
  {
    id: '7-cups',
    title: '7 Cups',
    category: 'Support',
    description: 'Find peer support and listening resources when you want a compassionate place to talk.',
    collection: 'Career Tools',
    tags: ['support', 'wellbeing', 'listening', 'mental health'],
    actionLabel: 'Visit 7 Cups',
    route: 'external',
    externalUrl: 'https://www.7cups.com/',
  },
  {
    id: 'atomic-habits',
    title: 'Atomic Habits',
    category: 'Books',
    description: 'A practical guide to changing habits through small, consistent improvements.',
    collection: 'Books',
    tags: ['habits', 'systems', 'discipline', 'self-improvement'],
    actionLabel: 'Read More',
    route: 'external',
    externalUrl: 'https://jamesclear.com/atomic-habits',
  },
  {
    id: 'deep-work',
    title: 'Deep Work',
    category: 'Books',
    description: 'A useful framework for focus, deliberate practice, and creating meaningful work.',
    collection: 'Books',
    tags: ['focus', 'productivity', 'work', 'deep focus'],
    actionLabel: 'Read More',
    route: 'external',
    externalUrl: 'https://www.calnewport.com/books/deep-work/',
  },
  {
    id: 'ted-talks-daily',
    title: 'TED Talks Daily',
    category: 'Podcasts',
    description: 'Short idea-rich talks that can spark reflection, curiosity, and fresh perspective.',
    collection: 'Podcasts',
    tags: ['ideas', 'inspiration', 'learning', 'perspective'],
    actionLabel: 'Listen',
    route: 'external',
    externalUrl: 'https://www.ted.com/podcasts',
  },
  {
    id: 'linkedin-learning',
    title: 'LinkedIn Learning',
    category: 'Career Tools',
    description: 'Skill-building courses and role guides for career growth and practical learning paths.',
    collection: 'Career Tools',
    tags: ['career', 'skills', 'courses', 'learning'],
    actionLabel: 'Visit LinkedIn Learning',
    route: 'external',
    externalUrl: 'https://www.linkedin.com/learning/',
  },
  {
    id: 'google-career-certificates',
    title: 'Google Career Certificates',
    category: 'Career Tools',
    description: 'Career-focused certificates to build job-ready skills and explore new pathways.',
    collection: 'Career Tools',
    tags: ['career', 'certificate', 'job skills', 'training'],
    actionLabel: 'Visit Google Careers',
    route: 'external',
    externalUrl: 'https://www.google.com/about/careers/applications/programs/career-certificates/',
  },
];
